[package]
name = "yomishi_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.25.0", features = ["derive"] }

[build-dependencies]
yomishi_config_gen.workspace = true
