[workspace]
members = ["yomishi-core", "yomishi-core/config_gen", "yomishi-core/config"]

[workspace.dependencies]
yomishi_config_gen = { path = "yomishi-core/config_gen" }
yomishi_config = { path = "yomishi-core/config" }
