[package]
name = "yomishi-core"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.9"
regex = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tonic = "0.9.2"
tokio = { version = "1.29.1", features = ["full"] } # TODO: don't use full

[build-dependencies]
tonic-build = "0.9.2"
