[package]
name = "yomishi-core"
version = "0.1.0"
build = "build.rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.9"
quick-xml = "0.30.0"
regex = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.29.1", features = ["full"] } # TODO: don't use full
tonic = "0.9.2"
tonic-web = "0.9.2"
zip = "0.6.6"

[build-dependencies]
tonic-build = "0.9.2"
